### ISSUE TITLE
Print button on a new window or Email Tab

### ISSUE THREAD

**Issue by jorgedlcruz** [Zimbra-Community/printpatch-zimlet#1]
After try the Zimlet, which works great, it will be possible to add the button "Print" in a new Email Window or in a new Tab.

That would be great!

**Comment by ghost** [comment]
I do not think it is possible due to another bug:

https://bugzilla.zimbra.com/show_bug.cgi?id=97496

I can look again, with new knowledge I may have, but I think Zimlets don't work well in new window period. For the tab maybe... but so far it has been fruitless efforts. I get this issue reported on all my zimlets :-p

**Comment by ghost** [comment]
May also be a documentation issue, menu's and buttons in different tabs, windows and all that stuff is complicated, that is why I created an example zimlet for it, that Zimbra refuses to merge.

https://bugzilla.zimbra.com/show_bug.cgi?id=101279

related:
https://bugzilla.zimbra.com/show_bug.cgi?id=103795
